baseURL = 'https://netzbremse.de/'
title = 'Netzbremse - Die Telekom drosselt das Netz!'

defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = false

[languages]
  [languages.de]
    languageName = 'Deutsch'
    weight = 1
  [languages.en]
    languageName = 'English'
    weight = 2

    title = 'Netzbremse - Deutsche Telekom is throttling the internet!'
    [languages.en.params]
      description = "If you are a customer of Deutsche Telekom and some websites just won't load, then we might have the solution to your problem!"
      socialShareImage = "/img/social_share.en.png"
      logoAlt = 'Magenta-colored hourglass symbol'
      [languages.en.params.hero]
        title = "Deutsche Telekom is throttling the internet. Let's do something about it!"
        subtitle = "If you are a customer of Deutsche Telekom and some websites just won't load, then we might have the solution to your problem!"
        [[languages.en.params.hero.links]]
          text = 'Complaint'
          url = 'https://epicenter.works/en/content/beschwerde-gegen-die-deutsche-telekom-wegen-verletzung-der-netzneutralitaet'
        [[languages.en.params.hero.links]]
          text = 'Press release'
          url = 'https://www.vzbv.de/pressemitteilungen/keine-zweiklassengesellschaft-im-internet-buendnis-reicht-beschwerde-gegen'
      [languages.en.params.footer]
        imprintURL = "https://epicenter.works/en/contact"
        privacyURL = "https://epicenter.works/en/privacy"
      [languages.en.params.newsletter]
        subscribeBTN = "Subscribe to Updates"

[params]
  shortTitle = 'Netzbremse'
  description = 'Wenn du Kund:in der Deutschen Telekom bist und manche Webseiten einfach nicht laden wollen, dann haben wir vielleicht die Lösung für dein Problem!'
  logo = "/img/hourglass.png"
  socialShareImage = "/img/social_share.png"
  logoAlt = "Magenta farbenes Sanduhr-Symbol"
  domain = "netzbremse.de"

[params.hero] 
  title = "Die Telekom drosselt das Netz. Tun wir etwas dagegen!"
  subtitle = "Wenn du Kund:in der Deutschen Telekom bist und manche Webseiten einfach nicht laden wollen, dann haben wir vielleicht die Lösung für dein Problem!"
  [[params.hero.links]]
    text = 'Beschwerde'
    url = 'https://epicenter.works/content/beschwerde-gegen-die-deutsche-telekom-wegen-verletzung-der-netzneutralitaet'
  [[params.hero.links]]
    text = 'Presseerklärung'
    url = 'https://www.vzbv.de/pressemitteilungen/keine-zweiklassengesellschaft-im-internet-buendnis-reicht-beschwerde-gegen'

[params.footer]
  imprintURL = "https://epicenter.works/kontakt"
  privacyURL = "https://epicenter.works/datenschutz"

[params.newsletter] 
  subscribeURL = "https://secure.dialog-mail.com/s/dyXMJ"
  subscribeBTN = "Updates Abonieren"

[params.icons]
  throw_on_error = true

[menus]
  [[menus.main]]
    name = 'Video'
    URL = '#video'
    weight = 10
  [[menus.main]]
    name = 'Newsletter'
    URL = '#newsletter'
    weight = 20
  [[menus.main]]
    name = 'Testimonials'
    URL = '#testimonials'
    weight = 30
  [[menus.main]]
    name = 'Unterstützung'
    URL = '#contact-us'
    weight = 40
  [[menus.main]]
    name = 'Presse'
    URL = '#media-coverage'
    weight = 50

[languages.en.menus]
  [[languages.en.menus.main]]
    name = 'Video'
    URL = '#video'
    weight = 10
  [[languages.en.menus.main]]
    name = 'Newsletter'
    URL = '#newsletter'
    weight = 20
  [[languages.en.menus.main]]
    name = 'Testimonials'
    URL = '#testimonials'
    weight = 30
  [[languages.en.menus.main]]
    name = 'Support'
    URL = '#contact-us'
    weight = 40
  [[languages.en.menus.main]]
    name = 'Press'
    URL = '#media-coverage'
    weight = 50

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

# Required setting for Tailwind 
# https://github.com/bep/hugo-starter-tailwind-basic
[module]
  [[module.imports]]
    path = "github.com/hugomods/icons/vendors/font-awesome"
  [[module.imports]]
    path = "github.com/hugomods/icons/vendors/tabler"
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/@fontsource/roboto/files"
    target = "static/fonts"
    includeFiles = "roboto-latin-*.woff2"
  [[module.mounts]]
    source = "node_modules/@fontsource/source-code-pro/files"
    target = "static/fonts"
    includeFiles = "*-latin-*.woff2"
  [[module.mounts]]
    source = "node_modules/lite-youtube-embed/src/"
    target = "assets/css/"
    includeFiles = "lite-yt-embed.css"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
