apiVersion: v1
kind: Namespace
metadata:
  name: netzbremse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netzbremse
  namespace: netzbremse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netzbremse
  template:
    metadata:
      labels:
        app: netzbremse
    spec:
      containers:
      - name: netzbremse
        image: ghcr.io/t-muehlberger/netzbremse.de:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr
---
apiVersion: v1
kind: Service
metadata:
  name: netzbremse
  namespace: netzbremse
spec:
  selector:
    app: netzbremse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netzbremse-ingress
  namespace: netzbremse
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - netzbremse'
spec:
  rules:
  - host: netzbremse.k1.muehlberger.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: netzbremse
            port:
              number: 80
  tls:
  - hosts:
    - netzbremse.k1.muehlberger.dev
    secretName: netzbremse-tls-secret


